### ISSUE TITLE
Error runing the script 

### ISSUE THREAD

**Issue by asantos01** [comprna/reorientexpress#1]
Hi,
i am trying to use the script but i got the next error:

  File "./reorientexpress.py", line 366
    <<<<<<<					HEAD
    ^
IndentationError: expected an indented block

how could i fix it ?

Thanks!

**Comment by angelrure** [comment]
Hi,
I just fixed that bug. Could you please use the new version and try again? Let us know if there is any other problem. Thanks!

**Comment by asantos01** [comment]
Hi,

Thanks, the new version is ok !
i ran de script and it worket well, but i was wondering if is possible to orient all my reads based in the output of reorientexpress? do you know some script to put all nanopore reads in the same strand sense?

Thanks in advance

**Comment by angelrure** [comment]
Hi, 
sorry for the delay. I'm not really sure I understand your question. 
The sequences from the output of reorientexpress are already oriented in the predicted correct orientation. Thus, all the sequences that are predicted to be in the wrong orientation, are complementary reversed. 

Does this solve your question? If it doesn't, could you please be more specific? 

Thank you
